# Answers


# 1 - Selection and summary statistics

In [107]:
tamanho = sales['zipcode'].unique().shape[0]
maximo = 0.0
media = 0.0
cep = 0
for i in range(tamanho):
    media = sales[sales['zipcode']==sales['zipcode'].unique()[i]]['price'].mean()
    if media > maximo:
        maximo = media
        cep = sales['zipcode'].unique()[i]
        
sales[sales['zipcode']==cep]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2974,3625049014,20140829T000000,2950000,4,3.50,4860,23885,2.0,0,0,...,12,4860,0,1996,0,98039,47.6172,-122.230,3580,16054
3761,2540700110,20150212T000000,1905000,4,3.50,4210,18564,2.0,0,0,...,11,4210,0,2001,0,98039,47.6206,-122.225,3520,18564
4077,3262300940,20141107T000000,875000,3,1.00,1220,8119,1.0,0,0,...,7,1220,0,1955,0,98039,47.6328,-122.236,1910,8119
4078,3262300940,20150210T000000,940000,3,1.00,1220,8119,1.0,0,0,...,7,1220,0,1955,0,98039,47.6328,-122.236,1910,8119
4149,6447300265,20141014T000000,4000000,4,5.50,7080,16573,2.0,0,0,...,12,5760,1320,2008,0,98039,47.6151,-122.224,3140,15996
4411,2470100110,20140804T000000,5570000,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
4791,2210500019,20150324T000000,937500,3,1.00,1320,8500,1.0,0,0,...,7,1320,0,1954,0,98039,47.6187,-122.226,2790,10800
5178,6447300345,20150406T000000,1160000,4,3.00,2680,15438,2.0,0,2,...,8,2680,0,1902,1956,98039,47.6109,-122.226,4480,14406
5589,6447300225,20141106T000000,1880000,3,2.75,2620,17919,1.0,0,1,...,9,2620,0,1949,0,98039,47.6144,-122.228,3400,14400
5880,2525049148,20141007T000000,3418800,5,5.00,5450,20412,2.0,0,0,...,11,5450,0,2014,0,98039,47.6209,-122.237,3160,17825
6868,3262300235,20141126T000000,1555000,5,2.50,2870,16238,2.0,0,0,...,8,2870,0,1962,0,98039,47.6308,-122.238,2870,16238
7501,2525049133,20150402T000000,1398000,5,2.25,2640,14959,1.0,0,0,...,7,1770,870,1929,0,98039,47.6191,-122.234,3240,17904
8241,3262301355,20140725T000000,1320000,3,2.75,2680,20104,1.0,0,0,...,9,1820,860,1964,0,98039,47.6304,-122.234,3060,19837
9254,9208900037,20140919T000000,6885000,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
9694,3262301610,20141118T000000,865000,3,1.50,1530,10827,1.0,0,0,...,8,1530,0,1955,0,98039,47.6354,-122.234,2050,10827
9809,5426300060,20141008T000000,1000000,3,2.25,2300,15952,1.0,0,0,...,8,1150,1150,1963,0,98039,47.6322,-122.232,2200,14284
11278,3025300226,20140515T000000,2100000,4,1.75,3550,19865,2.0,0,0,...,9,3550,0,1962,2002,98039,47.6236,-122.235,3000,19862
11952,2260300060,20150410T000000,2575000,5,3.00,4780,20440,1.0,0,0,...,10,3660,1120,1975,0,98039,47.6242,-122.239,4660,20440
12295,3738000070,20150309T000000,1712750,5,2.50,2660,6572,1.0,0,0,...,9,1960,700,1959,0,98039,47.6176,-122.223,3960,14595
12811,5425700150,20140804T000000,787500,4,1.75,1580,9382,1.0,0,0,...,7,1080,500,1963,0,98039,47.6353,-122.232,2010,9382
13235,3262300322,20150408T000000,1651000,4,3.25,3640,13530,1.0,0,0,...,9,2570,1070,1924,2000,98039,47.6293,-122.238,2760,15000
13267,5425700205,20140520T000000,1800000,4,3.50,4460,16953,1.0,0,0,...,9,2550,1910,1962,1994,98039,47.6338,-122.232,1980,13370
13419,2525049246,20141017T000000,1550000,2,2.25,2950,15593,1.0,0,0,...,8,1560,1390,1942,1986,98039,47.6209,-122.236,2060,19855
13621,2525049266,20140821T000000,1762000,3,2.25,3060,16000,2.0,0,0,...,10,3060,0,1988,0,98039,47.6189,-122.230,3510,13162
13988,5427110040,20140609T000000,1225000,4,2.50,2740,16007,2.0,0,0,...,9,2740,0,1984,0,98039,47.6353,-122.229,2760,16008
14052,7397300220,20140529T000000,2750000,4,3.25,4430,21000,2.0,0,0,...,10,4430,0,1952,2007,98039,47.6398,-122.237,3930,20000
14254,2425049107,20150305T000000,1950000,4,3.75,4150,17424,1.0,0,0,...,9,3130,1020,1963,2000,98039,47.6390,-122.236,3930,21420
14385,2425049061,20140825T000000,2200000,3,2.00,3570,30456,1.0,0,1,...,8,2070,1500,1946,1982,98039,47.6413,-122.240,3570,27418
14803,3835502815,20140925T000000,1260000,3,2.50,3110,9930,1.0,0,1,...,8,1640,1470,1954,0,98039,47.6112,-122.226,3650,14399
15022,2210500010,20140930T000000,2450000,7,4.25,4670,23115,2.0,0,2,...,11,4670,0,1992,0,98039,47.6183,-122.227,3240,13912
15255,2425049063,20140911T000000,3640900,4,3.25,4830,22257,2.0,1,4,...,11,4830,0,1990,0,98039,47.6409,-122.241,3820,25582
15632,3625049088,20140702T000000,2271150,4,3.25,4040,18916,1.0,0,0,...,9,4040,0,1954,0,98039,47.6155,-122.238,3000,18831
16268,3025300250,20150513T000000,1620000,4,2.25,2350,17709,2.0,0,0,...,9,2350,0,1977,0,98039,47.6232,-122.236,3360,19855
16302,7397300170,20140530T000000,3710000,4,3.50,5550,28078,2.0,0,2,...,12,3350,2200,2000,0,98039,47.6395,-122.234,2980,19602
16377,3262300920,20150408T000000,1200000,4,3.00,2150,8119,2.0,0,0,...,8,2150,0,1953,2004,98039,47.6335,-122.236,1590,8119
16825,3025300095,20141009T000000,2500000,4,4.50,4300,19844,2.0,0,0,...,11,4300,0,1985,1999,98039,47.6218,-122.237,3070,19845
17001,2525049259,20140812T000000,2187730,4,4.50,4240,13162,2.0,0,0,...,10,4240,0,2004,0,98039,47.6193,-122.229,3010,12163
17209,3025300225,20141031T000000,1450000,5,2.75,3090,19865,1.0,0,0,...,9,3090,0,1953,0,98039,47.6232,-122.235,2970,19862
17230,2470200020,20140514T000000,1880000,4,2.75,3260,19542,1.0,0,0,...,10,2170,1090,1968,0,98039,47.6245,-122.236,3480,19863
17899,3262300555,20140708T000000,2458000,4,5.25,6500,14986,2.0,0,0,...,11,5180,1320,2001,0,98039,47.6304,-122.236,2270,8119
17930,3625049079,20140801T000000,1350000,3,2.00,2070,9600,1.0,0,1,...,7,1590,480,1946,0,98039,47.6160,-122.239,3000,16215
18793,2525049263,20140709T000000,2680000,5,3.00,4290,20445,2.0,0,0,...,11,4290,0,1985,0,98039,47.6217,-122.239,3620,22325
18892,5427100150,20140626T000000,1410000,4,2.25,3250,16684,2.0,0,0,...,9,3250,0,1979,0,98039,47.6334,-122.229,2890,16927
18912,2425049066,20140616T000000,1920000,4,2.50,3070,34412,1.0,0,3,...,9,2070,1000,1950,0,98039,47.6400,-122.240,3780,27940
19148,3625049042,20141011T000000,3635000,5,6.00,5490,19897,2.0,0,0,...,12,5490,0,2005,0,98039,47.6165,-122.236,2910,17600
19236,2525049086,20141003T000000,2720000,4,3.25,3990,18115,2.0,0,0,...,11,3990,0,1989,0,98039,47.6177,-122.229,3450,16087
19351,2525049113,20140725T000000,1950000,4,3.50,4065,18713,2.0,0,0,...,10,4065,0,1987,0,98039,47.6209,-122.237,3070,18713
20096,3262300485,20150421T000000,2250000,5,5.25,3410,8118,2.0,0,0,...,11,3410,0,2006,0,98039,47.6295,-122.236,3410,16236
21040,6447300365,20141113T000000,2900000,5,4.00,5190,14600,2.0,0,1,...,11,5190,0,2013,0,98039,47.6102,-122.225,3840,19250
21514,3262300818,20150227T000000,1865000,4,3.75,3790,8797,2.0,0,0,...,11,3290,500,2006,0,98039,47.6351,-122.236,2660,12150

In [108]:
maximo

2160606.6

# 2 - Filtering data

In [124]:
casas = sales[np.logical_and(sales['sqft_living']<=4000, sales['sqft_living']>2000)]
casas

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
10,1736800520,20150403T000000,662500,3,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
15,9297300055,20150124T000000,650000,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
21,2524049179,20140826T000000,2000000,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
22,7137970340,20140703T000000,285000,5,2.50,2270,6300,2.0,0,0,...,8,2270,0,1995,0,98092,47.3266,-122.169,2240,7005
24,3814700200,20141120T000000,329000,3,2.25,2450,6500,2.0,0,0,...,8,2450,0,1985,0,98030,47.3739,-122.172,2200,6865
26,1794500383,20140626T000000,937000,3,1.75,2450,2691,2.0,0,0,...,8,1750,700,1915,0,98119,47.6386,-122.360,1760,3573
29,1873100390,20150302T000000,719000,4,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
30,8562750320,20141110T000000,580500,3,2.50,2320,3980,2.0,0,0,...,8,2320,0,2003,0,98027,47.5391,-122.070,2580,3980
32,461000390,20140624T000000,687500,4,1.75,2330,5000,1.5,0,0,...,7,1510,820,1929,0,98117,47.6823,-122.368,1460,5000
34,7955080270,20141203T000000,322500,4,2.75,2060,6659,1.0,0,0,...,7,1280,780,1981,0,98058,47.4276,-122.157,2020,8720
35,9547205180,20140613T000000,696000,3,2.50,2300,3060,1.5,0,0,...,8,1510,790,1930,2002,98115,47.6827,-122.310,1590,3264
37,2768000400,20141230T000000,640000,4,2.00,2360,6000,2.0,0,0,...,8,2360,0,1904,0,98107,47.6702,-122.362,1730,4700
39,2078500320,20140620T000000,605000,4,2.50,2620,7553,2.0,0,0,...,8,2620,0,1996,0,98056,47.5301,-122.180,2620,11884
40,5547700270,20140715T000000,625000,4,2.50,2570,5520,2.0,0,0,...,9,2570,0,2000,0,98074,47.6145,-122.027,2470,5669
42,7203220400,20140707T000000,861990,5,2.75,3595,5639,2.0,0,0,...,9,3595,0,2014,0,98053,47.6848,-122.016,3625,5639
45,8035350320,20140718T000000,488000,3,2.50,3160,13603,2.0,0,0,...,8,3160,0,2003,0,98019,47.7443,-121.977,3050,9232
47,4178300310,20140716T000000,785000,4,2.50,2290,13416,2.0,0,0,...,9,2290,0,1981,0,98007,47.6194,-122.151,2680,13685
49,822039084,20150311T000000,1350000,3,2.50,2753,65005,1.0,1,2,...,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
51,7231300125,20150217T000000,345000,5,2.50,3150,9134,1.0,0,0,...,8,1640,1510,1966,0,98056,47.4934,-122.189,1990,9133
54,4217401195,20150303T000000,920000,5,2.25,2730,6000,1.5,0,0,...,8,2130,600,1927,0,98105,47.6571,-122.281,2730,6000
55,9822700295,20140512T000000,885000,4,2.50,2830,5000,2.0,0,0,...,9,2830,0,1995,0,98105,47.6597,-122.290,1950,5000
56,9478500640,20140819T000000,292500,4,2.50,2250,4495,2.0,0,0,...,7,2250,0,2008,0,98042,47.3663,-122.114,2250,4500
57,2799800710,20150407T000000,301000,3,2.50,2420,4750,2.0,0,0,...,8,2420,0,2003,0,98042,47.3663,-122.122,2690,4750
58,7922800400,20140827T000000,951000,5,3.25,3250,14342,2.0,0,4,...,8,3250,0,1968,0,98008,47.5880,-122.116,2960,11044
60,1516000055,20141210T000000,650000,3,2.25,2150,21235,1.0,0,3,...,8,1590,560,1959,0,98166,47.4336,-122.339,2570,18900
62,5072410070,20141021T000000,505000,3,1.75,2519,8690,2.0,0,0,...,8,2519,0,1973,0,98166,47.4428,-122.344,2500,9500
65,3253500160,20141120T000000,317625,3,2.75,2770,3809,1.5,0,0,...,7,1770,1000,1925,0,98144,47.5747,-122.304,1440,4000
66,3394100030,20140909T000000,975000,4,2.50,2720,11049,2.0,0,0,...,10,2720,0,1989,0,98004,47.5815,-122.192,2750,11049
67,3717000160,20141009T000000,287000,4,2.50,2240,4648,2.0,0,0,...,7,2240,0,2005,0,98001,47.3378,-122.257,2221,4557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21537,1043000100,20141211T000000,370000,4,2.50,2531,6843,2.0,0,0,...,8,2531,0,2013,0,98030,47.3850,-122.189,2604,6238
21542,3874900085,20150227T000000,715000,4,3.25,2630,7770,2.0,0,0,...,9,2630,0,2014,0,98126,47.5459,-122.377,1370,7770
21544,8562770720,20150423T000000,589999,3,2.50,2140,3628,2.0,0,0,...,8,1960,180,2006,0,98027,47.5370,-122.074,2280,2812
21546,9211010300,20140707T000000,509900,3,2.50,3030,9053,2.0,0,0,...,8,3030,0,2009,0,98059,47.4945,-122.149,3010,6026
21548,8835770330,20140819T000000,1057000,2,1.50,2370,184231,2.0,0,0,...,11,2370,0,2005,0,98045,47.4543,-121.778,3860,151081
21553,2522059251,20150409T000000,465000,3,2.50,2050,15035,2.0,0,0,...,9,2050,0,2006,0,98042,47.3619,-122.122,1300,15836
21554,2855000110,20140808T000000,388000,3,2.50,2198,6222,2.0,0,2,...,8,2198,0,2010,0,98198,47.3906,-122.304,2198,7621
21558,2255500123,20140820T000000,747450,3,2.50,2110,1339,2.0,0,0,...,8,1410,700,2014,0,98122,47.6088,-122.311,1630,2670
21560,423059387,20141118T000000,540000,5,2.50,3370,4850,2.0,0,0,...,9,3370,0,2007,0,98056,47.5078,-122.169,2900,5570
21562,2122059216,20150414T000000,422000,4,2.50,2930,5973,2.0,0,0,...,10,2930,0,2008,0,98030,47.3846,-122.186,3038,7095
21563,9406530090,20141020T000000,337000,4,2.50,2470,5100,2.0,0,0,...,8,2470,0,2005,0,98038,47.3622,-122.041,2240,5123
21564,7168100015,20141009T000000,579950,5,2.75,3080,5752,2.0,0,0,...,9,3080,0,2014,0,98059,47.4922,-122.153,3000,4650
21565,5007500120,20150226T000000,341780,4,2.75,2260,4440,2.0,0,0,...,7,2260,0,2014,0,98001,47.3507,-122.291,2260,4563
21568,524059330,20150130T000000,1700000,4,3.50,3830,8963,2.0,0,0,...,10,3120,710,2014,0,98004,47.5990,-122.197,2190,10777
21571,3345700207,20150502T000000,608500,4,3.50,2850,5577,2.0,0,0,...,8,1950,900,2014,0,98056,47.5252,-122.192,2850,5708
21573,8562790760,20140520T000000,785000,4,3.50,3070,4684,2.0,0,0,...,10,2190,880,2009,0,98027,47.5316,-122.076,2290,2664
21575,9578500790,20141111T000000,399950,3,2.50,3087,5002,2.0,0,0,...,8,3087,0,2014,0,98023,47.2974,-122.349,2927,5183
21580,7853420110,20141003T000000,594866,3,3.00,2780,6000,2.0,0,0,...,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000
21581,7853420110,20150504T000000,625000,3,3.00,2780,6000,2.0,0,0,...,9,2780,0,2013,0,98065,47.5184,-121.886,2850,6000
21589,7570050450,20140910T000000,347500,3,2.50,2540,4760,2.0,0,0,...,8,2540,0,2010,0,98038,47.3452,-122.022,2540,4571
21591,4140940150,20141002T000000,572000,4,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641
21594,5087900040,20141017T000000,350000,4,2.75,2500,5995,2.0,0,0,...,8,2500,0,2008,0,98042,47.3749,-122.107,2530,5988
21596,7502800100,20140813T000000,679950,5,2.75,3600,9437,2.0,0,0,...,9,3600,0,2014,0,98059,47.4822,-122.131,3550,9421
21597,191100405,20150421T000000,1575000,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21598,8956200760,20141013T000000,541800,4,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500
21599,7202300110,20140915T000000,810000,4,3.00,3990,7838,2.0,0,0,...,9,3990,0,2003,0,98053,47.6857,-122.046,3370,6814
21603,7852140040,20140825T000000,507250,3,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21605,3448900210,20141014T000000,610685,4,2.50,2520,6023,2.0,0,0,...,9,2520,0,2014,0,98056,47.5137,-122.167,2520,6023
21606,7936000429,20150326T000000,1007500,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200

In [126]:
casas.shape[0]/sales.shape[0]

0.42187572294452413

# 3 - Building a regression model with several more features

In [129]:
advanced_features = [
'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'zipcode',
'condition', # condition of house
'grade', # measure of quality of construction
'waterfront', # waterfront property
'view', # type of view
'sqft_above', # square feet above ground
'sqft_basement', # square feet in basement
'yr_built', # the year built'yr_renovated', # the year renovated
'lat', 'long', # the lat-long of the parcel
'sqft_living15', # average sq.ft. of 15 nearest neighbors
'sqft_lot15', # average lot size of 15 nearest neighbors
]

x_train = train_data[advanced_features].values.reshape(-1,len(advanced_features))
y_train = train_data['price'].values.reshape(-1,1)

mult_model = linear_model.LinearRegression()
mult_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [130]:
x_test = test_data[advanced_features].values.reshape(-1,len(advanced_features))
y_test = test_data['price'].values.reshape(-1,1)

y_pred = mult_model.predict(x_test)

In [131]:
print('intercept:', mult_model.intercept_, 'coefficients:', mult_model.coef_)
# The mean squared error
print("RMSE: %.2f" % (rmse(y_pred, y_test)))

intercept: [ 8355574.94114961] coefficients: [[ -3.89175069e+04   4.65356559e+04   1.14160658e+02   1.55625102e-01
    5.30062861e+03  -6.06139549e+02   2.21778020e+04   9.38696764e+04
    6.17740285e+05   5.09808670e+04   6.98475352e+01   4.43131237e+01
   -2.74816838e+03   6.01490912e+05  -2.22902745e+05   2.14654122e+01
   -4.20099024e-01]]
RMSE: 193866.47

In [132]:
249311.90 - rmse(y_pred, y_test)

55445.429793712654